version: "3"
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    env_file:
      - /var/www/wm_webapp/.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 7811:7811
