version: "3"
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 7811:7811
