name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    
    - name: Up the Docker image
      run: docker-compose up -d
